modules_cpp =\
  Modules/MAction/ImprovedStaggered.cpp \
  Modules/MAction/ImprovedStaggered5D.cpp \
  Modules/MContraction/ASlashMesonField.cpp \
  Modules/MContraction/Meson.cpp \
  Modules/MContraction/MesonField.cpp \
  Modules/MContraction/MesonField_old.cpp \
  Modules/MFermion/GaugeProp.cpp \
  Modules/MFermion/SpinTaste.cpp \
  Modules/MGauge/StochEmFunc.cpp \
  Modules/MIO/SaveVector.cpp \
  Modules/MNoise/FullVolumeSpinColorDiagonal.cpp \
  Modules/MNoise/TimeDilutedSpinColorDiagonal.cpp \
  Modules/MSolver/A2AVectors.cpp \
  Modules/MSolver/ImplicitlyRestartedLanczos.cpp \
  Modules/MSolver/LowModeProj.cpp \
  Modules/MSolver/MixedPrecisionCG.cpp \
  Modules/MSolver/MixedPrecisionRBPrecCG.cpp \
  Modules/MSolver/RBPrecCG.cpp \
  Modules/MSource/RandomWall.cpp \
  Modules/MSource/SeqAslash.cpp \
  Modules/MUtilities/EigenPackExtractEvals.cpp \
  Modules/MUtilities/ModifyEigenPack.cpp

modules_hpp =\
  Modules/MAction/ImprovedStaggered.hpp \
  Modules/MAction/ImprovedStaggered5D.hpp \
  Modules/MContraction/ASlashMesonField.hpp \
  Modules/MContraction/Meson.hpp \
  Modules/MContraction/MesonField.hpp \
  Modules/MContraction/MesonField_old.hpp \
  Modules/MFermion/GaugeProp.hpp \
  Modules/MFermion/SpinTaste.hpp \
  Modules/MGauge/StochEmFunc.hpp \
  Modules/MIO/SaveVector.hpp \
  Modules/MNoise/FullVolumeSpinColorDiagonal.hpp \
  Modules/MNoise/TimeDilutedSpinColorDiagonal.hpp \
  Modules/MSolver/A2AVectors.hpp \
  Modules/MSolver/ImplicitlyRestartedLanczos.hpp \
  Modules/MSolver/LowModeProj.hpp \
  Modules/MSolver/MixedPrecisionCG.hpp \
  Modules/MSolver/MixedPrecisionRBPrecCG.hpp \
  Modules/MSolver/RBPrecCG.hpp \
  Modules/MSource/RandomWall.hpp \
  Modules/MSource/SeqAslash.hpp \
  Modules/MUtilities/EigenPackExtractEvals.hpp \
  Modules/MUtilities/ModifyEigenPack.hpp

